#!/usr/bin/env bash
# Start the Feishu ComfyUI bot. Activates the venv, loads .env, and runs comfyui-feishu.
set -euo pipefail

cd "$(dirname "$0")"

if [[ ! -d .venv ]]; then
  echo "未找到 .venv，请先执行：python3 -m venv .venv && source .venv/bin/activate && pip install -e '.[dev]'" >&2
  exit 1
fi

if [[ ! -f .env ]]; then
  echo "未找到 .env，请先 cp .env.example .env 并填入 FEISHU_APP_ID / FEISHU_APP_SECRET" >&2
  exit 1
fi

# shellcheck disable=SC1091
source .venv/bin/activate

# Trust corporate root CAs (in addition to certifi's bundle) by pointing
# requests / urllib / OpenSSL at a combined bundle of certifi + macOS keychains.
# Regenerated by scripts/build_ca_bundle.sh.
if [[ -f data/ca-bundle.pem ]]; then
  export SSL_CERT_FILE="$PWD/data/ca-bundle.pem"
  export REQUESTS_CA_BUNDLE="$PWD/data/ca-bundle.pem"
fi

# .env is loaded by pydantic-settings (see src/comfyui_feishu/config.py),
# so no need to `source` it here.
exec comfyui-feishu
